### ISSUE TITLE
[Feature] Create backend API to register users

### ISSUE THREAD

**Issue by rodneyosodo** [JKUATSES/votingBooth#6]
**Is your feature request related to a problem? Please describe.**
There is no backend API to register users

**Describe the solution you'd like**
Create backend API to register users

POST | /api/v1/auth/signup | Creates user account
-- | -- | --

**Additional context**
#### Awesome :star::star::star::star::star:
```json
{
  "user": {
    "name": "john doe",
    "email": "john.doe@students.jkuat.ac.ke",
    "token": "jwt.token.here",
    "regno": "exx211-00xx/2020",
    "mobileno": "+2547xxxxxxxx"
  }
}
```
No authentication required, returns User data

Required fields: email, password, username, regno, mobileno

**Comment by rodneyosodo** [comment]
Working on this

**Comment by ObaraEmmanuel** [comment]
Hello @0x6f736f646f , I just now noticed you are working on this. I started working on it yesterday and I have basically finished it. Should I just drop it or can I take it off your hands?

**Comment by rodneyosodo** [comment]
You can submit the pull request. No problem

**Comment by rodneyosodo** [comment]
Done by #39 
@ObaraEmmanuel you need to write now tests for the changes you have pushed if you are conversant with T.D.D. If not we will write while undertaking development.
But I am closing the issue for now
